# Generated by Django 3.2.5 on 2021-09-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('pk',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
